### ISSUE TITLE
Incorrect behaviour on Android devices

### ISSUE THREAD

**Issue by vguzev** [sanniassin/react-input-mask#11] opened 2015-10-14 12:19 UTC
Try to run your examples http://sanniassin.github.io/react-input-mask/demo.html on Android devices.
They are all broken...

**Comment by sanniassin** [comment] 2015-10-14 20:55
@vguzev Can you provide more detailed report? Device model, Android version, used browser and it's version and what exactly is broken? I can see some issues with backspace, but i want make sure that nothing else missed.

**Comment by vguzev** [comment] 2015-10-15 08:45
Generally, Chrome for Android doesn't support "keypress" events. Don't use Anroid emulators, use real devices to reproduce this (I used Android Lollipop). Generally you cannot rely on onKeypress events because different input methods can be used, like IME (when you type part of the word and system offers you different variants, then you click on one of these words) or soft keyboards... 

Handling this is a common problem of all "masked inputs" for React I've seen... 
In case of react-input-mask when you type something focus position is not changing or changing incorrectly. That's why you can see some strange errors like when you type "12345" you see "15432"... or symbols cannot be typed at all because the focus is in the end of the word.

P.S. Here you can see how someone found workaround here: http://therealmofcode.com/posts/2014/03/where-is-keypress-event-chrome-android.html

**Comment by sanniassin** [comment] 2015-10-17 11:35
@vguzev It should be fixed in latest version, but i have no real Android devices and debug with Genymotion.

Can you also test current react-input-mask version (0.3.1) on real device?

**Closed** 2015-10-22 11:53 UTC

**Comment by reintroducing** [comment] 2015-12-09 15:42
@sanniassin I'm late to this party but what version was this fix applied in? I had 0.4.1 running in my code base and customers were reporting issues inputting on Android devices.  I'll upgrade right now to 0.5.6 (latest) but it sounds like this should have been fixed before 0.4.1 in which case it isn't apparently.  I'd love to provide more info but I was just told this by our customer service team and don't have details on what device was used, unfortunately.

**Comment by sanniassin** [comment] 2015-12-23 17:56
@vguzev Try 0.5.10 too. I've made some android-related improvements and i doubt, that anything more could be done because of totally screwed input events in android.

**Comment by flynfish** [comment] 2016-01-22 17:45
I just tested the demo on Android 5.1.1 and Firefox 43 and it isn't working correctly.

**Comment by andre0799** [comment] 2016-07-30 21:59
This should be reopen. It doesn't work on many Android browsers

**Comment by sanniassin** [comment] 2016-08-06 06:49
@andre0799 It's better to open specific issues for your cases and describe there what is not working, where it's not working and how to reproduce it.
