### ISSUE TITLE
Caret moving to next to last position on Chrome android

### ISSUE THREAD

**Issue by dusnoki** [sanniassin/react-input-mask#51] opened 2016-07-29 21:01 UTC
I have an issue with the component. When using it with a standard desktop web browser i don't have this issue. But on Android when the last character is entered (from the limit) the caret moves back 1 space.

You can see it I made a screen capture on my phone.

https://www.dropbox.com/s/2o2ltd35uca165b/2016_07_29_22_40_38_22_50_29_22_51_58_22_54_21_22_54_59.gif?dl=0

**Comment by sanniassin** [comment] 2016-08-06 06:42
@dusnoki Need more info to reproduce:
* Device model
* Android version
* Browser version

Can you also try this pen – http://codepen.io/sanniassin/pen/vKVvVX to make sure it's not related to your code?

**Comment by dusnoki** [comment] 2016-08-08 09:46
Device model: Note 4 (N910F)
Android Version: 6.0.1 Marshmallow
Browser version: Chrome 52.0.2743.98

I tried this pen and it also has the same results... caret moves one position back when last char is entered.

**Comment by sanniassin** [comment] 2016-08-10 10:01
@dusnoki Thank you. I have no Android devices and can't reproduce this issue in [Genymotion](https://www.genymotion.com/), so i need your help to fix it. Can you investigate into it and make a PR or find an emulator which will be able to reproduce?

**Comment by dusnoki** [comment] 2016-08-11 11:44
I tried the codepen on firefox and android stock browser and they seem to work fine... Only chrome is giving me this issue. I'll try to investigate what is the problem.

**Comment by IlanaB** [comment] 2016-08-15 16:43
I am also experiencing this issue. It's not reproducible in desktop but on Samsung Galaxy S7 Edge on Chrome v46. When adding the last character to the mask the cursor stays in the second last position and the field doesn't validate properly with the shown value.

**Comment by sanniassin** [comment] 2016-08-16 12:48
@IlanaB @dusnoki Are you using native Android keyboard or TouchWiz one or something else?

**Comment by IlanaB** [comment] 2016-08-16 15:49
@sanniassin I am using the native keyboard

**Comment by sanniassin** [comment] 2016-08-16 19:38
@IlanaB @dusnoki Is it fixed in this pen? http://codepen.io/sanniassin/pen/dXAvyd

**Comment by IlanaB** [comment] 2016-08-16 20:06
I'm struggling to use that pen from my device. It's hiding the input field
so I can't see it as I am typing
Is it possible to add some space to the bottom below the input so that i
can scroll down?

**Comment by sanniassin** [comment] 2016-08-16 20:12
@IlanaB Usually rotating phone to landscape helps. I've also commited fix so you can try it in your project.

**Comment by sanniassin** [comment] 2016-08-19 07:37
@IlanaB @dusnoki Does it working fine now?

**Comment by IlanaB** [comment] 2016-08-19 14:02
@sanniassin I won't be able to confirm until next week, thank you for looking into this so quickly though!

**Comment by sanniassin** [comment] 2016-08-19 17:12
@IlanaB You're welcome. I'll wait, just want to be sure before publishing update on npm.

**Comment by sanniassin** [comment] 2016-09-04 05:52
@IlanaB @dusnoki I'll close this issue as it seems to be fixed. Let me know if it not.

**Closed by sanniassin** 2016-09-04 05:52 UTC

**Comment by dusnoki** [comment] 2016-09-19 13:37
@sanniassin it is working fine in the new codepen. Thnx for the fix guys :)
